function result=getValItems(username, password, setname, varname)

%/*
%*
%*		Author:			Dr. Maik Lorch
%*		Email:			maik.lorch@kit.edu; maik.lorch@lorch-group.de
%*		Version:		MTP2017
%*
%*		Keine Verwendung / Änderung ohne Rücksprache
%*		No usage / edit without permission
%*/

    result=urlread(getURL(), 'POST',...
   {'username', username,...
    'passwort', password,...
    'prozedur', 'p_getVals',...
    'vtyp1','string',...
    'variable1', username,...
    'vtyp2','string',...
    'variable2', password,...    
    'vtyp3','string',...
    'variable3', setname,...
    'vtyp4','string',...
    'variable4', varname}...
    );

    

end