function result=getVal(username, password, setname, varname, datatype)

%/*
%*
%*		Author:			Dr. Maik Lorch
%*		Email:			maik.lorch@kit.edu; maik.lorch@lorch-group.de
%*		Version:		MTP2017
%*
%*		Keine Verwendung / �nderung ohne R�cksprache
%*		No usage / edit without permission
%*/

result=urlread(getURL(), 'POST',...
   {'username', username,...
    'passwort', password,...
    'prozedur', 'p_getVal',...
    'vtyp1','string',...
    'variable1', username,...
    'vtyp2','string',...
    'variable2', password,...    
    'vtyp3','string',...
    'variable3', setname,...
    'vtyp4','string',...
    'variable4', varname,...
    'vtyp5','string',...
    'variable5', datatype}...
    );

    k=strfind(result, '[');

[a,b]=size(result);
json=result(k(1):b);
result2json=loadjson(json);

result=str2double(result2json{1}.value);

end