function result=saveValItem(username, password, setname, varname, value, datatype, row, col)

%/*
%*
%*		Author:			Dr. Maik Lorch
%*		Email:			maik.lorch@kit.edu; maik.lorch@lorch-group.de
%*		Version:		MTP2017
%*
%*		Keine Verwendung / �nderung ohne R�cksprache
%*		No usage / edit without permission
%*/

    result=urlread(getURL(), 'POST',...
   {'username', username,...
    'passwort', password,...
    'prozedur', 'p_saveValItem',...
    'vtyp1','string',...
    'variable1', username,...
    'vtyp2','string',...
    'variable2', password,...    
    'vtyp3','string',...
    'variable3', setname,...
    'vtyp4','string',...
    'variable4', varname,...
    'vtyp5','string',...
    'variable5', value,...
    'vtyp6','string',...
    'variable6', datatype,...
    'vtyp7','zahl',...
    'variable7', num2str(row),...
    'vtyp8','zahl',...
    'variable8', num2str(col)}...
    );

k=strfind(result, '[');
%k(1);
[a,b]=size(result);
json=result(k(1):b);
if strcmp(json,'[]')
    result=['saved var: ' varname];
end

end